location: UK SOUTH
name: trustmarque
automation:
  runbook:
    keyVaultName: kvaultcorerg
    certificateName: democertificate2
    keyVaultCertificatePassword: password1
    sourceControl:
      url: https://github.com/Trustmarque/cloudmarque-azure-pwsh.git
      type: github
      keyVaultPersonalAccessToken: githubPAT
      folderPath: /Cloudmarque.Azure/Private/Runbooks
      branch: iaas_tagging_auto_delete