location: UK South
name: coreAccount
service:
  dependencies:
    keyvault:
  publish:
    resourceGroup:
    automation:

automation:
  runbook:
    certificateName:                                              # Optional: Name of Certificate in Key Vault.
    keyVaultCertificatePasswordSecretName:                        # Optional: Keyvault secret which contains password. This will be used for certificate. This can be overwritten by passing cmdline password
    service:
      dependencies:
        keyvault:
    sourceControl:
      keyVaultPersonalAccessToken:                                # Optional: (only if repoURL): keyvault secret name for PAT to access Repo.
      url:                                                        # Optional: For repo intergration.
      type:                                                       # Optional: (only if repoURL): github | git | tvfc.
      branch:                                                     # Optional: Branch to pull from. Not required for tvfc. Default is master.
      folderPath:                                                 # Optional: (only if repoURL): Path to folder which contains runbook or DSC files.
  dsc:
    certificateName:                                              # Optional: Name of Certificate in Key Vault.
    keyVaultCertificatePasswordSecretName:                        # Optional: Keyvault secret which contains password. This will be used for certificate. This can be overwritten by passing cmdline password
    service:
      dependencies:
        keyvault:
    sourceControl:
      keyVaultPersonalAccessToken:                                # Optional (only if repoURL): keyvault secret name for PAT to access Repo.
      url:                                                        # Optional: For repo intergration.
      type:                                                       # Optional (only if repoURL): github | git | tvfc.
      branch:
      folderPath: