location: UK South
enableUkNhs: false 
service:
  dependencies:
    workspace:
    
securityContacts:
  primary:
    email:                  # First set of contact details can have an email and phone set.
    phone: 
  additionalEmails: []